import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from '../src/models/Product';

dotenv.config();

const img = (id: string, w = 800, h = 800) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&auto=format`;

const products = [
  {
    slug: "amazon-prime-mystery-tech-package-xl",
    name: "Amazon Prime Mystery Tech Box (10-in-1 Bundle)",
    brand: "Amazon Surplus",
    category: "Amazon Mystery Packages",
    price: 89,
    originalPrice: 199,
    condition: "Unopened Liquidation Box",
    warranty: "30 Days Guarantee",
    inStock: true,
    rating: 4.9,
    reviews: 1420,
    images: [img("1586528116311-ad8dd3c8310d"), img("1526170375885-4d8ecf77b99f"), img("1583863788434-e58a36330cf6")],
    description: "A mystery mega-box directly from Amazon surplus returns & overstock. Every sealed bundle contains 10 authentic items including power banks, earpods, high-speed cables, smart gadgets, and surprise tech tools valued over $200!",
    features: ["Guaranteed 10 high-value tech items", "Includes power bank, wireless earbuds & fast cables", "Verified functional stock", "Factory overstock & customer returns mix", "Massive savings vs retail price"],
    specs: { "Bundle Size": "10 Tech Items", "Est. Retail Value": "$200 - $250", "Condition": "Mixed New & Sealed Overstock", "Package Weight": "2.8 kg" },
    featured: true,
  },
  {
    slug: "greek-yogurt-maker-fermentation-station",
    name: "Greek Yogurt Maker & Fermentation Machine",
    brand: "Dash",
    category: "Home & Kitchen Gadgets",
    price: 45,
    originalPrice: 59,
    color: "Alpine White",
    colorHex: "#f4f4f5",
    condition: "Brand New",
    warranty: "1 Year Official",
    inStock: true,
    rating: 4.8,
    reviews: 620,
    images: [img("1556911220-e15b29be8c8f"), img("1584308666744-24d5c474f2ae")],
    description: "Make thick, high-protein Greek yogurt at home effortlessly. Features precise digital temperature control, ultra-fine stainless steel whey strainer, and a 1.5L BPA-free batch container.",
    features: ["1.5L Total Capacity", "Ultra-fine stainless steel Greek strainer", "Microprocessor temp control (8-12 hr timer)", "Auto shutoff with end chime", "Dishwasher-safe components"],
    specs: { "Capacity": "1.5 Liters", "Power": "25W Energy Efficient", "Container": "BPA-Free Tritan & Stainless Mesh", "Timer Range": "1 - 24 Hours" },
    featured: true,
  },
  {
    slug: "nitecore-10000lm-tactical-camping-flashlight",
    name: "High-Lumen Rechargeable Tactical Flashlight & Power Bank",
    brand: "Nitecore",
    category: "Outdoor & Tactical",
    price: 39,
    originalPrice: 55,
    color: "Matte Black",
    colorHex: "#1c1c1e",
    condition: "Brand New",
    warranty: "2 Years Official",
    inStock: true,
    rating: 4.9,
    reviews: 890,
    images: [img("1508873696983-2df515122519"), img("1510557880182-3d4d3cba35a5")],
    description: "Blazing 10,000-lumen emergency camping light and tactical flashlight with a built-in 5,000mAh power bank to charge your phone in the wild. IPX8 waterproof aerospace aluminum body.",
    features: ["10,000 Max Lumens output (500m beam depth)", "Built-in 5,000mAh emergency reverse power bank", "IPX8 Waterproof & 2m impact resistant", "5 Brightness modes + Strobe & SOS signal", "OLED digital status screen"],
    specs: { "Lumens": "10,000 LM max", "Battery": "5000 mAh Li-ion", "Waterproof": "IPX8 Submersible", "Weight": "280g" },
    featured: true,
  },
  {
    slug: "xiaomi-fitness-band-pro-hr",
    name: "Xiaomi Fitness Band Pro (Heart Rate & SpO2)",
    brand: "Xiaomi",
    category: "Smart Gadgets & Fitness",
    price: 49,
    originalPrice: 69,
    color: "Midnight Black",
    colorHex: "#2b2b2f",
    condition: "Brand New",
    warranty: "1 Year Official",
    inStock: true,
    rating: 4.7,
    reviews: 2150,
    images: [img("1575311373937-040b8e1fd5b6"), img("1523275335684-37898b6baf30")],
    description: "Track your sleep, workouts, heart rate, and blood oxygen with a crisp 1.62\" Always-On AMOLED screen. Waterproof to 50 meters with up to 14 days battery life per charge.",
    features: ["1.62\" AMOLED Always-On HD display", "Continuous Heart Rate & SpO2 monitoring", "120+ Fitness and sports modes", "5ATM Water resistance (50m)", "14-Day ultra long battery life"],
    specs: { "Display": "1.62\" AMOLED, 490x192 px", "Sensors": "PPG Heart Rate, 3-Axis Gyro, SpO2", "Battery": "190 mAh (14 Days typical)", "Connectivity": "Bluetooth 5.3 BLE" },
    featured: true,
  },
  {
    slug: "anker-737-power-bank-24000mah-140w",
    name: "Anker 737 PowerCore 24,000mAh 140W Power Bank",
    brand: "Anker",
    category: "Chargers & Power",
    price: 119,
    originalPrice: 149,
    color: "Space Charcoal",
    colorHex: "#3a3a3c",
    condition: "Brand New",
    warranty: "18 Months Official",
    inStock: true,
    rating: 4.9,
    reviews: 3100,
    images: [img("1583863788434-e58a36330cf6"), img("1609091839311-d5365f9ff1c5")],
    description: "Supercharge your phone, tablet, or laptop on the go! Equipped with Power Delivery 3.1 and bi-directional 140W fast charging. Features a smart digital display showing live power output.",
    features: ["24,000mAh Ultra-high capacity", "140W Ultra-fast multi-port output", "Smart digital display for wattage & battery %", "Charges a phone up to 5 times", "ActiveShield 2.0 temperature protection"],
    specs: { "Capacity": "24,000 mAh / 86.4 Wh", "Ports": "2x USB-C PD 3.1, 1x USB-A", "Max Output": "140W Total", "Weight": "630g" },
    featured: true,
  },
  {
    slug: "baseus-7-in-1-usbc-hub-adapter",
    name: "Baseus 7-in-1 USB-C Multiport Hub & Adapter",
    brand: "Baseus",
    category: "Cables & Hubs",
    price: 34,
    originalPrice: 49,
    color: "Space Gray",
    colorHex: "#7d7d80",
    condition: "Brand New",
    warranty: "1 Year Official",
    inStock: true,
    rating: 4.8,
    reviews: 1840,
    images: [img("1544716278-ca5e3f4abd8c"), img("1585790050230-5dd28404ccb9")],
    description: "Expand a single USB-C port into a 4K@60Hz HDMI video port, 100W Power Delivery charging port, SD/MicroSD card readers, and 3x high-speed USB 3.0 ports.",
    features: ["4K @ 60Hz HDMI video output", "100W Power Delivery pass-through", "5Gbps USB 3.0 data transfer speeds", "Dual SD & TF card slots", "Aluminum alloy heat-dissipating shell"],
    specs: { "Inputs": "USB-C Braided Cable", "Outputs": "1x HDMI, 1x USB-C PD, 3x USB 3.0, 1x SD, 1x TF", "Resolution": "Up to 4K UHD 3840x2160 @ 60Hz", "Material": "Anodized Aluminum" },
    featured: true,
  },
  {
    slug: "sony-wf-1000xm5-wireless-earpods",
    name: "Sony WF-1000XM5 Wireless Noise-Canceling Earpods",
    brand: "Sony",
    category: "Audio & Earpods",
    price: 249,
    originalPrice: 299,
    color: "Black",
    colorHex: "#181819",
    condition: "Brand New",
    warranty: "1 Year Official",
    inStock: true,
    rating: 4.9,
    reviews: 1980,
    images: [img("1590658268037-6bf12165a8df"), img("1600294037681-c80b4cb5b434")],
    description: "World-class active noise cancellation driven by Sony's Integrated Processor V2. High-Res Audio Wireless sound with crystal clear calls and up to 24 hours playback with the case.",
    features: ["Industry-leading Noise Canceling (V2 Processor)", "Dynamic Driver X for rich vocals & deep bass", "AI-based noise reduction for crystal clear calls", "8hr earbud battery + 16hr charging case", "Multipoint connection (pair 2 devices)"],
    specs: { "Driver": "8.4mm Dynamic Driver X", "ANC": "Dual Processor Noise Canceling", "Battery Life": "Up to 24 hours total", "Codecs": "LDAC, AAC, SBC, LC3" },
    featured: true,
  },
  {
    slug: "gopro-hero12-black-action-camera",
    name: "GoPro HERO12 Black 5.3K Action Camera",
    brand: "GoPro",
    category: "Cameras & Tech",
    price: 349,
    originalPrice: 399,
    color: "Midnight Blue Accent",
    colorHex: "#1f2937",
    condition: "Brand New",
    warranty: "1 Year Official",
    inStock: true,
    rating: 4.8,
    reviews: 1150,
    images: [img("1526170375885-4d8ecf77b99f"), img("1512499617640-c74ae3a79d37")],
    description: "Capture incredible 5.3K video and 27MP photos with HyperSmooth 6.0 video stabilization. Waterproof to 33 feet out of the box, HDR video, and Bluetooth audio support.",
    features: ["5.3K60, 4K120, and 2.7K240 Video", "Emmy-winning HyperSmooth 6.0 Stabilization", "Rugged + Waterproof to 33ft (10m)", "HDR Video & Photos", "27MP Photos with RAW export"],
    specs: { "Sensor": "1/1.9\" CMOS", "Video": "5.3K @ 60fps / 4K @ 120fps", "Battery": "1720 mAh Enduro Battery", "Storage": "MicroSD UHS-I (Up to 512GB)" },
    featured: true,
  },
  {
    slug: "ugreen-100w-gan-fast-wall-charger",
    name: "Ugreen 100W 4-Port GaN Fast Wall Charger",
    brand: "Ugreen",
    category: "Chargers & Power",
    price: 54,
    originalPrice: 74,
    color: "Space Gray",
    colorHex: "#4a4a4c",
    condition: "Brand New",
    warranty: "1 Year Official",
    inStock: true,
    rating: 4.7,
    reviews: 1450,
    images: [img("1583863788434-e58a36330cf6"), img("1544716278-ca5e3f4abd8c")],
    description: "Power up to 4 devices simultaneously! Advanced Gallium Nitride (GaN) technology allows 100W maximum power delivery in a compact, portable foldaway plug body.",
    features: ["100W High-speed total output", "3x USB-C ports + 1x USB-A port", "GaN Tech for cooler, smaller charging", "Universal fast charging protocol support", "Foldable wall plug"],
    specs: { "Power": "100W Max Output", "Technology": "GaN Fast Tech", "Ports": "3x USB-C (PD 3.0), 1x USB-A (QC 4.0)", "Dimensions": "69 x 69 x 33 mm" },
  },
  {
    slug: "anker-100w-braided-usbc-cables-4pack",
    name: "Anker Nylon Braided 100W Fast Charge Cable Pack (4-Pack)",
    brand: "Anker",
    category: "Cables & Hubs",
    price: 22,
    originalPrice: 32,
    color: "Black & Silver",
    colorHex: "#27272a",
    condition: "Brand New",
    warranty: "18 Months Official",
    inStock: true,
    rating: 4.8,
    reviews: 2900,
    images: [img("1544716278-ca5e3f4abd8c"), img("1585790050230-5dd28404ccb9")],
    description: "Tangle-free double-braided nylon cables engineered to handle 100W ultra-fast charging and 12,000+ bends. Includes 2x 3ft, 1x 6ft, and 1x 10ft lengths.",
    features: ["100W (20V/5A) Power Delivery support", "12,000+ Lifespan bend tested", "Double-braided armored nylon jacket", "E-Marker smart chip built-in", "Includes 4 cables in assorted lengths"],
    specs: { "Quantity": "4 Cables (3ft, 3ft, 6ft, 10ft)", "Max Power": "100W Power Delivery", "Data": "480 Mbps USB 2.0" },
  },
  {
    slug: "amazon-overstock-gadget-box-small",
    name: "Amazon Surplus Electronics Mystery Box (5 Items)",
    brand: "Amazon Surplus",
    category: "Amazon Mystery Packages",
    price: 49,
    originalPrice: 110,
    condition: "Surplus Liquidation",
    warranty: "30 Days Guarantee",
    inStock: true,
    rating: 4.6,
    reviews: 780,
    images: [img("1586528116311-ad8dd3c8310d"), img("1590658268037-6bf12165a8df")],
    description: "Budget-friendly Amazon overstock package! Contains 5 surprise functional consumer tech items such as Bluetooth adapters, car mounts, LED lights, power accessories, and audio gear.",
    features: ["5 Guaranteed tech & accessory items", "Retail value $110+", "100% functional inspected surplus", "Fun unboxing experience"],
    specs: { "Item Count": "5 Products", "Condition": "Unopened Overstock / Open Box", "Package Weight": "1.4 kg" },
  },
  {
    slug: "jbl-wave-flex-true-wireless-earpods",
    name: "JBL Wave Flex True Wireless Deep Bass Earpods",
    brand: "JBL",
    category: "Audio & Earpods",
    price: 59,
    originalPrice: 79,
    color: "Deep White",
    colorHex: "#e4e4e7",
    condition: "Brand New",
    warranty: "1 Year Official",
    inStock: true,
    rating: 4.6,
    reviews: 940,
    images: [img("1590658268037-6bf12165a8df"), img("1523275335684-37898b6baf30")],
    description: "Bring your sound everywhere with 12mm drivers featuring JBL Deep Bass Sound. Ergonomic stick-open design, IP54 water & dust resistance, and up to 32 hours total battery.",
    features: ["JBL Deep Bass Sound (12mm drivers)", "32 Hours total battery (8h + 24h case)", "Speed charge: 10 mins = 2 hours playback", "Hands-free calls with VoiceAware", "IP54 Splash & Dust proof"],
    specs: { "Driver": "12mm Dynamic", "Battery Life": "8h earbuds + 24h case", "Waterproof": "IP54 Earbuds / IPX2 Case", "Bluetooth": "Version 5.2" },
  },
  {
    slug: "nitecore-solar-camping-lantern-sos",
    name: "Solar Powered Camping Lantern & Emergency Light",
    brand: "Nitecore",
    category: "Outdoor & Tactical",
    price: 29,
    originalPrice: 42,
    color: "Forest Green",
    colorHex: "#15803d",
    condition: "Brand New",
    warranty: "1 Year Official",
    inStock: true,
    rating: 4.8,
    reviews: 530,
    images: [img("1508873696983-2df515122519"), img("1586528116311-ad8dd3c8310d")],
    description: "Collapsible 360-degree soft illumination camping light powered by top-mounted solar panel or USB-C. Features red night vision mode and emergency SOS beacon.",
    features: ["360-Degree warm ambient light", "Dual solar + USB-C fast charging", "Red light night mode + emergency strobe", "Magnetic base + folding hang hook", "Compact collapsible housing"],
    specs: { "Lumens": "600 Lumens max", "Battery": "4400 mAh Solar Li-ion", "Run Time": "Up to 48 hours on low" },
  },
  {
    slug: "xiaomi-smart-wifi-security-camera-2k",
    name: "Xiaomi Smart Wi-Fi 2K Security Camera (360° Pan-Tilt)",
    brand: "Xiaomi",
    category: "Cameras & Tech",
    price: 38,
    originalPrice: 49,
    color: "White",
    colorHex: "#ffffff",
    condition: "Brand New",
    warranty: "1 Year Official",
    inStock: true,
    rating: 4.7,
    reviews: 1320,
    images: [img("1526170375885-4d8ecf77b99f"), img("1598327105666-5b89351aff97")],
    description: "Keep an eye on your home in crystal-clear 2K HD. 360° pan-tilt-zoom motor, AI human detection tracking, infrared night vision, and two-way voice calling.",
    features: ["2K Ultra-HD Resolution (1296p)", "360° Horizontal & 108° Vertical view", "AI Human detection and motion tracking", "Infrared night vision with zero glow", "Two-way real-time voice audio"],
    specs: { "Resolution": "2304 x 1296 (2K HD)", "Storage": "MicroSD up to 256GB / Cloud", "Connectivity": "2.4GHz Wi-Fi" },
  },
  {
    slug: "baseus-magnetic-wireless-powerbank-10000mah",
    name: "Baseus Magnetic Wireless Power Bank 10,000mAh",
    brand: "Baseus",
    category: "Chargers & Power",
    price: 42,
    originalPrice: 59,
    color: "Starlight Silver",
    colorHex: "#e2e8f0",
    condition: "Brand New",
    warranty: "1 Year Official",
    inStock: true,
    rating: 4.7,
    reviews: 1620,
    images: [img("1583863788434-e58a36330cf6"), img("1609091839311-d5365f9ff1c5")],
    description: "Snap-on 15W MagSafe-compatible wireless fast charging with strong N52 magnets, built-in foldable metal kickstand, and a 20W PD USB-C port.",
    features: ["15W Wireless magnetic auto-align charging", "20W USB-C PD fast cable charging", "Foldable metal kickstand for video watching", "10,000mAh slim compact size", "Pass-through charging enabled"],
    specs: { "Capacity": "10,000 mAh", "Wireless": "15W / 10W / 7.5W MagSafe", "USB-C Out": "20W Power Delivery" },
  },
  {
    slug: "dash-automatic-express-cold-brew-machine",
    name: "Automatic Express Cold Brew & Drink Maker",
    brand: "Dash",
    category: "Home & Kitchen Gadgets",
    price: 68,
    originalPrice: 89,
    color: "Graphite Gray",
    colorHex: "#374151",
    condition: "Brand New",
    warranty: "1 Year Official",
    inStock: false,
    rating: 4.5,
    reviews: 410,
    images: [img("1556911220-e15b29be8c8f"), img("1584308666744-24d5c474f2ae")],
    description: "Rapid cold extraction technology brews smooth cold brew coffee or iced tea infusions in just 9 minutes instead of 24 hours. Digital touch display with strength selector.",
    features: ["Rapid 9-minute cold brew extraction", "Digital touch panel with 3 strength levels", "Stainless steel micro-mesh filter", "42oz (1.2L) borosilicate glass carafe", "One-touch clean cycle"],
    specs: { "Capacity": "1.2 Liters (42 oz)", "Time": "9 - 15 Minutes", "Filter": "Reusable Stainless Mesh" },
  },
];

const seedProducts = async () => {
  try {
    const MONGODB_URI = process.env.MONGODB_URI;
    if (!MONGODB_URI) throw new Error('MONGODB_URI is not defined.');

    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    let created = 0;
    let skipped = 0;

    for (const product of products) {
      const exists = await Product.findOne({ slug: product.slug });
      if (exists) {
        console.log(`  Skipped (already exists): ${product.name}`);
        skipped++;
      } else {
        await Product.create(product);
        console.log(`  Created: ${product.name}`);
        created++;
      }
    }

    console.log(`\nDone! Created: ${created}, Skipped: ${skipped}`);
    process.exit(0);
  } catch (error) {
    console.error('Error seeding products:', error);
    process.exit(1);
  }
};

seedProducts();
